# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-02 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='teacher/%Y/%m', verbose_name='\u8bb2\u5e08\u5934\u50cf'),
        ),
    ]
